url: https://studiofarley.com
baseurl: /dingen/

# Site settings
title: Studio Farley
email: james@studiofarley.com
description: "Creative design with strategy by Studio Farley."

# Build settings
markdown: kramdown
permalink: pretty